Address slf4j warnings
jethronap/jstat pull request #27
Opened 2019-09-19 18:01 UTC by jethronap

pls consider this PR on order to close corresponding issue.

2019-09-21 14:17 UTC, pockerman requested changes
If you merge this branch into the master...all items marked as green will be merged also :) :) However you don't want that....

2019-09-21 14:17 UTC, pockerman commented on pom.xml
> +        <dependency>
so this is the only change required???

2019-09-25 21:07 UTC, jethronap commented on pom.xml
> +        <dependency>
yes this gets rid of the warning.

2019-09-25 21:07 UTC, jethronap commented
resolved conflicts I think we're good to go.

2019-09-26 06:09 UTC, pockerman requested changes
I think we sould delete this branch altogether. We simply add the ```slf4j``` in ```pom.xml``` and yet there are all these changes.  If we simply branch off from the current master and do the change things will be simpler. What do you think?

2019-09-26 07:11 UTC, jethronap commented
ok I'll put these changes in create_visualization_classes. in its pom.xml and then I'll delete this branch

2019-09-26 07:16 UTC, closed without merging